#!/bin/bash
self="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. .env

true '
  -w /data/debug\
  -e DJANGO_SETTINGS_MODULE=pynoser.settings \
  -e PYTHONPATH=/opt/pynoser\
'

# run 'pynoser-unittest-run reader' to only run pynoser tests (no django)

docker run -i -t\
  -w /opt/pynoser\
  --rm ${PYNOSER_IMAGE}\
  /opt/pynoser/pynoser/manage.py test "$@"

echo $?
