#!/bin/bash
ERR_LEVEL=3
ERR_INTVL="1 hours"
ERR_THRESH_PER_INTVL=10

errors=$(
python -u /opt/pynoser/pynoser/manage.py dbshell <<EOF
select count(*) from djutil_errorlog
where log_level>=${ERR_LEVEL}
  and time_stamp > datetime('now', 'localtime', '-${ERR_INTVL}')
EOF
) 2>&1 || exit 42

echo -n "${errors} errors  in the last ${ERR_INTVL}."

if [[ $errors -ge $ERR_THRESH_PER_INTVL ]]; then
    echo " Failed!"
    exit 1
fi

exit 0
